# docker exec -it mongodb1 /bin/bash
# mongosh -u root -p example
# 192.168.64.1 替换为你的 IP
# rs.initiate({_id:"mongos", members:[{_id:0, host:"192.168.64.1:27017"}, {_id:1, host:"192.168.64.1:27018"}, {_id:2, host:"192.168.64.1:27019"}]})
version: '3.3'

services:
  mongodb1:
    image: mongo:6.0
    volumes:
      - ./script/mongo/key:/data/mongodb.key
    user: root
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=webook
    container_name: mongodb1
    ports:
      - 27017:27017
    command: mongod --replSet mongos --keyFile /data/mongodb.key
    restart: always
    entrypoint:
      - bash
      - -c
      - |
        chmod 400 /data/mongodb.key
        chown 999:999 /data/mongodb.key
        exec docker-entrypoint.sh $$@

  mongodb2:
    image: mongo:6.0
    volumes:
      - ./script/mongo/key:/data/mongodb.key
    user: root
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=webook
    container_name: mongodb2
    ports:
      - 27018:27017
    command: mongod --replSet mongos --keyFile /data/mongodb.key
    restart: always
    entrypoint:
      - bash
      - -c
      - |
        chmod 400 /data/mongodb.key
        chown 999:999 /data/mongodb.key
        exec docker-entrypoint.sh $$@

  mongodb3:
    image: mongo:6.0
    volumes:
      - ./script/mongo/key:/data/mongodb.key
    user: root
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=webook
    container_name: mongodb3
    ports:
      - 27019:27017
    command: mongod --replSet mongos --keyFile /data/mongodb.key
    restart: always
    entrypoint:
      - bash
      - -c
      - |
        chmod 400 /data/mongodb.key
        chown 999:999 /data/mongodb.key
        exec docker-entrypoint.sh $$@