// Code generated by MockGen. DO NOT EDIT.
// Source: ./ranking_service.go
//
// Generated by this command:
//
//	mockgen -source=./ranking_service.go -package=svcmocks -destination=./mocks/ranking_service.mock.go RankingService
//
// Package svcmocks is a generated GoMock package.
package svcmocks

import (
	context "context"
	reflect "reflect"

	domain "gitee.com/geekbang/basic-go/webook/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRankingService is a mock of RankingService interface.
type MockRankingService struct {
	ctrl     *gomock.Controller
	recorder *MockRankingServiceMockRecorder
}

// MockRankingServiceMockRecorder is the mock recorder for MockRankingService.
type MockRankingServiceMockRecorder struct {
	mock *MockRankingService
}

// NewMockRankingService creates a new mock instance.
func NewMockRankingService(ctrl *gomock.Controller) *MockRankingService {
	mock := &MockRankingService{ctrl: ctrl}
	mock.recorder = &MockRankingServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRankingService) EXPECT() *MockRankingServiceMockRecorder {
	return m.recorder
}

// GetTopN mocks base method.
func (m *MockRankingService) GetTopN(ctx context.Context) ([]domain.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopN", ctx)
	ret0, _ := ret[0].([]domain.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopN indicates an expected call of GetTopN.
func (mr *MockRankingServiceMockRecorder) GetTopN(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopN", reflect.TypeOf((*MockRankingService)(nil).GetTopN), ctx)
}

// TopN mocks base method.
func (m *MockRankingService) TopN(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TopN", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// TopN indicates an expected call of TopN.
func (mr *MockRankingServiceMockRecorder) TopN(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TopN", reflect.TypeOf((*MockRankingService)(nil).TopN), ctx)
}
